export const RECIEVE_PURCHASE_SUMMARY = "RECIEVE_PURCHASE_SUMMARY";
export const SET_LOADING = "SET_LOADING";
export const VALIDATE_PROMO_CODE = "VALIDATE_PROMO_CODE";
export const INVALID_PROMO = "INVALID_PROMO";
export const SET_APPLIED_PROMO_CODE="SET_APPLIED_PROMO_CODE";